name: sls-deploy
description: Deploys a Serverless Framework service
inputs:
  stage:
    description: Stage to be deployed to
    required: true
  aws-account-id:
    description: AWS Account Id of target environment
    required: true
  aws-region:
    description: AWS region to deploy to
    required: false
    default: us-east-1

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/trade-game-backend-DeployerRole
        role-session-name: gha_deployer
        aws-region: ${{ inputs.aws-region }}

    - name: Deploy backend
      shell: bash
      run: |
        npm install
        AWS_ACCOUNT_ID=${{ inputs.aws-account-id }} npm run deploy -- --conceal --stage ${{ inputs.stage }}