name: Remove Backend Dev

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  # PR number
  VERSION: pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2
      - name: 'Removing backend stage: ${{ env.VERSION }}'
        uses: './.github/actions/sls-remove'
        with:
          stage: ${{ env.VERSION }}
          aws-account-id: ${{ secrets.DEV_AWS_ACCOUNT_ID }}